### ISSUE TITLE
转发参数 bug

### ISSUE THREAD

**Issue by liaoxian95175141** [tangyoha/telegram_media_downloader#100]
/forward https://t.me/c/src_chat https://t.me/c/dst_chat 100 400 [Filter]
转发参数 设定100 400 并不会转发第100条到400条 消息 而是转发第100条消息后的400条消息 
就是说设定100 400 实际上转发的是第100条消息到第500条消息  
而且我想转发20条消息 设置成 100 20 还不可以 后面的参数必须大于前面的 这就很尴尬

**Comment by tangyoha** [comment]
#116
