### ISSUE TITLE
[Bug]: new version 2.2.1

### ISSUE THREAD

**Issue by Romntic** [tangyoha/telegram_media_downloader#102]
### telegram_media_downloader version or commit

2.2.1

### What OS are you seeing the problem on?

Mac

### Python Version

3.11.5

### What happened?

i cant make install from terminal 
this file coming for me when i download 
![Screen Shot 2023-08-30 at 2 48 42 AM](https://github.com/tangyoha/telegram_media_downloader/assets/31198048/6be9e318-1894-4c0b-b7a5-b243413fd7f6)

### Expected Behavior

i think its differnet apps 

### Current Behavior

still not working

**Comment by tangyoha** [comment]
not support mac now
