### ISSUE TITLE
[Feature]: 在web监控页面添加一个重启服务的按钮。

### ISSUE THREAD

**Issue by songquanxu** [tangyoha/telegram_media_downloader#103]
### Description

如题：在web监控页面除了“暂停‘按钮，添加一个“重启服务”的按钮，方便在连接服务器的情况下停止服务并重新开始。

### Suggested Solution

点击”重启服务“后，首先需要弹出确认，而后重启服务，重启成功后自动刷新页面。

**Comment by tangyoha** [comment]
重启目前没有好的方案，暂时不做
