### ISSUE TITLE
[Feature]: Only download assets from a specific topic

### ISSUE THREAD

**Issue by doio** [tangyoha/telegram_media_downloader#105]
### Description

There are numerous topics in a group, and if I specify the `chat_id` as well as the range, for example, `download_filter: id >= 8244 && id <= 8262`, videos from other topics in this group will also be downloaded because they may have been multi-uploading to different topics. 

Since the `chat_id` for all the topics in the group is the same, is there anyway the applet can identify and download the assets (images/videos/etc.) only from specific topics, like `https://t.me/c/1745040687/9840` and `https://t.me/c/1745040687/49` respectively? 

### Suggested Solution

A way to download assets only from a specific topic in a group without id range.

**Comment by tangyoha** [comment]
@doio hi,what means topic?

**Comment by doio** [comment]
> @doio hi,what means topic?

I think it's essentially a group, but the contents for each topic is divided by topic tags and they are different and can be easily navigated to?

Ref.
https://telegram.org/blog/topics-in-groups-collectible-usernames

Perhaps, another way to download at the moment is by specifying the hashtag that's in each topic?

**Comment by jpleite** [comment]
Would love that feature too

**Comment by tangyoha** [comment]
@doio hi, This is a good feature!

**Comment by tangyoha** [comment]
try reply_to_message_id

**Comment by tangyoha** [comment]
d94ee7a

**Comment by jpleite** [comment]
Hi @tangyoha This feature is marked as closed. Can you explain how to use it and download from a specific topic?

**Comment by tangyoha** [comment]
@jpleite hi, we add filter `reply_to_message_id` for this, try use bot cmd `/get_info` to get `reply_to_message_id` value.

**Comment by tangyoha** [comment]
@jpleite hi, if you like this project, please give a star.

**Comment by doio** [comment]
Tested just now but getting `None`  @_@

Never mind... somehow it works now. Essentially it's again the last number after the slash when you copy a topic link. Will try and download to verify. 

Edit: Still doesn't seem to work at all. Will always download from the first messages, even if `id` and `reply_to_message_id` are present in `download_filter:`

```yaml
chat:
- chat_id: -1001852030835
  last_read_message_id: 9752
  download_filter: reply_to_message_id == 9840 && id >= 9841 && id <= 10080
```

**Comment by tangyoha** [comment]
we will test late

**Comment by tangyoha** [comment]
![image](https://github.com/tangyoha/telegram_media_downloader/assets/39958403/cb4a55c4-0ae0-4cc1-934b-509e609634e7)

@doio  hi, There is no problem in the test. Before downloading, check data.yaml to see if there are any tasks that have not been downloaded before.

**Comment by doio** [comment]
@tangyoha Oh, didn't know about the data.yml and the fact that it keeps unfinished failed download IDs. Cleared the file and it seems... It works now! 

You could actually append the filter to bot commands, didn't know about that either. However when I typed like your command in the picture, I got this instead and no downloads were initiating: 

`from CHANNEL_NAME download message id = 1 - 0 !` 

I wonder why's that.

**Comment by tangyoha** [comment]
@doio hi, I will close this issue. please ask question in telegram group.

**Comment by Firebug24k** [comment]
Hi, this feature has stopped working again, can you check it?  Always reply_to_message_id: None
