### ISSUE TITLE
[Bug]: 转发设置范围无效

### ISSUE THREAD

**Issue by nyancatda** [tangyoha/telegram_media_downloader#112]
### telegram_media_downloader version or commit

v2.2.1

### What OS are you seeing the problem on?

Other Linux Distro

### Python Version

Docker

### What happened?

使用Bot模式时，通过转发指令尝试转发单条消息时发现设置范围无效

### Expected Behavior

使用指令`/forward https://t.me/c/xxxxx me 1112276 1112276`转发消息时只转发id为`1112276`这一条消息

### Current Behavior

实际转发时，却出现将`1112276`到`0`的全部消息都被转发了，即使设置`/forward https://t.me/c/xxxxx me 1112275 1112276`，也依然是转发了`1112275`到`0`的所有消息

**Comment by tangyoha** [comment]
后面还有几个消息呢

**Comment by nyancatda** [comment]
包含从指定ID到最新消息的全部消息

**Comment by tangyoha** [comment]
#116
