### ISSUE TITLE
[Bug]: fail to detect/download "Hide with Spoiler" images/videos

### ISSUE THREAD

**Issue by ghost** [tangyoha/telegram_media_downloader#113]
### telegram_media_downloader version or commit

 v2.2.1

### What OS are you seeing the problem on?

Windows

### What happened?

"Hide with Spoiler"功能说明https://www.youtube.com/watch?v=WnreGyr1a0c

无论tdl.exe或Bot里面/download都无法下载，bot显示为
📥 下载: 0.0b
├─ 📁 总数: 0
├─ ✅ 成功: 0
├─ ❌ 失败: 0
└─ ⏩ 跳过: 0

### Expected Behavior

"Hide with Spoiler" images/videos can be downloaded as well

### Current Behavior

"Hide with Spoiler" images/videos cannot be downloaded

**Comment by tangyoha** [comment]
@matiuplraep hi，I will check late.

**Comment by tangyoha** [comment]
实际测试可以下载

**Comment by ghost** [comment]
你好，我建了频道channel测试了下，最新版仍然无法下载，要怎么设置呢

用get_info测试的上传的图片／视频如启用“Hide with Spoiler”，识别不了

`Group/Channel
├─ id: -1002107612401
├─ first name: None
├─ last name: None
└─ name: None
Message
├─ message_date: 2023-11-02 22:14:51
├─ message_id: 3
├─ message_caption: None
├─ media_file_size: None
├─ media_width: None
├─ media_height: None
├─ media_file_name: None
├─ media_duration: None
├─ id: 3
├─ caption: None
├─ file_size: None
├─ file_name: None
├─ media_type: None
├─ file_extension: None
├─ sender_id: None
├─ sender_name: None
├─ reply_to_message_id: None`

**Comment by tangyoha** [comment]
这个为什么什么都获取不了

**Comment by ghost** [comment]
> 这个为什么什么都获取不了

https://www.reddit.com/r/Telegram/comments/122lt0u/api_can_i_get_an_image_with_a_spoiler/?rdt=52528
你好，这个不知道有没有帮助

**Comment by tangyoha** [comment]
@matiuplraep hi， 你能在telegram创建一个群，并弄一个最小的实例提供给我测试吗

**Comment by ghost** [comment]
> @matiuplraep hi， 你能在telegram创建一个群，并弄一个最小的实例提供给我测试吗

channel
https://t.me/+dnJgumKXQKRhZjZl

/get_info https://t.me/c/2052527049/2
`Group/Channel
├─ id: -1002052527049
├─ first name: None
├─ last name: None
└─ name: None
Message
├─ message_date: 2023-11-05 22:30:54
├─ message_id: 2
├─ message_caption: None
├─ media_file_size: None
├─ media_width: None
├─ media_height: None
├─ media_file_name: None
├─ media_duration: None
├─ id: 2
├─ caption: None
├─ file_size: None
├─ file_name: None
├─ media_type: None
├─ file_extension: None
├─ sender_id: None
├─ sender_name: None
├─ reply_to_message_id: None`
/get_info https://t.me/c/2052527049/3
`Group/Channel
├─ id: -1002052527049
├─ first name: None
├─ last name: None
└─ name: None
Message
├─ message_date: 2023-11-05 22:33:23
├─ message_id: 3
├─ message_caption: None
├─ media_file_size: None
├─ media_width: None
├─ media_height: None
├─ media_file_name: None
├─ media_duration: None
├─ id: 3
├─ caption: None
├─ file_size: None
├─ file_name: None
├─ media_type: None
├─ file_extension: None
├─ sender_id: None
├─ sender_name: None
├─ reply_to_message_id: None`

**Comment by tangyoha** [comment]
@matiuplraep  hi,实际测试没有问题
![image](https://github.com/tangyoha/telegram_media_downloader/assets/39958403/1f7c8c8c-d13f-4285-baa8-81504e69091d)

**Comment by tangyoha** [comment]
@matiuplraep hi，你使用的是什么登录的，用的bot_token登录的吗

**Comment by matiuplraep** [comment]
> https://t.me/+dnJgumKXQKRhZjZl

我是用手机登陆的，难道是手机问题吗。。。

**Comment by ghost** [comment]
> @matiuplraep hi，你使用的是什么登录的，用的bot_token登录的吗

用手机号码登录的，用bot_token会报错bad_request_400.ChannelInvalid: [400 CHANNEL_INVALID]: The channel parameter is invalid (caused by "channels.GetChannels")。。。

**Comment by tangyoha** [comment]
是要用手机号登录 ，不能用bot token ，使用的tdl版本是多少

**Comment by ghost** [comment]
> 是要用手机号登录 ，不能用bot token ，使用的tdl版本是多少

最新版 2。23


api id api hash 自己建的
```

file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
file_path_prefix:
- chat_title
- media_datetime
media_types:
- audio
- photo
- video
- document
- voice
- video_note
- animation
disable_syslog:
- INFO
proxy:
  hostname: 127.0.0.1
  port: 10808
  scheme: socks5
language: ZH
max_download_task: 5
web_host: 127.0.0.1
web_port: 5000
save_path: D:\Documents\tdl-win64\tdl\downloads
```

**Comment by tangyoha** [comment]
使用的是release 里面的压缩包可执行文件 还是直接python运行？

**Comment by ghost** [comment]
> 使用的是release 里面的压缩包可执行文件 还是直接python运行？

直接运行release里面的可执行文件

**Comment by ghost** [comment]
> 使用的是release 里面的压缩包可执行文件 还是直接python运行？

python 3.10.5运行也不行

**Comment by tangyoha** [comment]
用python 运行的话，需要 执行 pip3 install https://github.com/tangyoha/pyrogram/archive/refs/heads/master.zip

**Comment by tangyoha** [comment]
后续稳定后我才会提交到主干，你可以先测试下

**Comment by ghost** [comment]
> 后续稳定后我才会提交到主干，你可以先测试下

> 用python 运行的话，需要 执行 pip3 install https://github.com/tangyoha/pyrogram/archive/refs/heads/master.zip

先运行了这个

然后测试了下 可以了 图片和影片经测试可下载👏
