### ISSUE TITLE
[Feature]: 希望加个文件命名时可以过滤关键字

### ISSUE THREAD

**Issue by ikalt** [tangyoha/telegram_media_downloader#114]
### Description

有的caption很长，里面有很多无关信息，例如@XXX，关注XXX，亦或者无用标签名称或广告，希望加个可以文件命名时可以过滤某些关键字，不会因为大量无关信息和文件名长度限制，导致文件本身信息保留不全

### Suggested Solution

no

### Alternatives

no

**Comment by tangyoha** [comment]
@ikalt hi，能否举例说明想怎么过滤

**Comment by tangyoha** [comment]
长时间不回复，关闭issue
