### ISSUE TITLE
[Bug]: No module named 'moviepy'

### ISSUE THREAD

**Issue by jerryc127** [tangyoha/telegram_media_downloader#119]
### telegram_media_downloader version or commit

v2.2.3,2023-10-30

### What OS are you seeing the problem on?

Other Linux Distro

### Python Version

v2.2.3,2023-10-30

### What happened?

telegram_media_downloader  | Traceback (most recent call last):
telegram_media_downloader  |   File "/app/media_downloader.py", line 15, in <module>telegram_media_downloader  |     from module.bot import start_download_bot, stop_download_bot
telegram_media_downloader  |   File "/app/module/bot.py", line 28, in <module>
telegram_media_downloader  |     from module.pyrogram_extension import (
telegram_media_downloader  |   File "/app/module/pyrogram_extension.py", line 16, in <module>
telegram_media_downloader  |     from moviepy.audio.io.AudioFileClip import AudioClip
telegram_media_downloader  | ModuleNotFoundError: No module named 'moviepy'

### Expected Behavior

work fine

### Current Behavior

telegram_media_downloader  | Traceback (most recent call last):
telegram_media_downloader  |   File "/app/media_downloader.py", line 15, in <module>telegram_media_downloader  |     from module.bot import start_download_bot, stop_download_bot
telegram_media_downloader  |   File "/app/module/bot.py", line 28, in <module>
telegram_media_downloader  |     from module.pyrogram_extension import (
telegram_media_downloader  |   File "/app/module/pyrogram_extension.py", line 16, in <module>
telegram_media_downloader  |     from moviepy.audio.io.AudioFileClip import AudioClip
telegram_media_downloader  | ModuleNotFoundError: No module named 'moviepy'

**Comment by tangyoha** [comment]
docker？ 不是docker 重新安装下依赖就可以了

**Comment by tangyoha** [comment]
pip3 install -r requirements.txt

**Comment by jerryc127** [comment]
> docker？ 不是docker 重新安装下依赖就可以了

是 docker 安装

**Comment by tangyoha** [comment]
> > docker？ 不是docker 重新安装下依赖就可以了
> 
> 
> 
> 是 docker 安装

docker最新版本我修复了这个问题的啊 提供下具体版本 我确认下

**Comment by jerryc127** [comment]
没事了
一直都是 watchtower 监控升级的
没给我升级到最新版
自己检查了下
升级了
