### ISSUE TITLE
[Feature]: 有考虑支持一下其他客户端的媒体下载吗？

### ISSUE THREAD

**Issue by tinet-jutt** [tangyoha/telegram_media_downloader#123]
### Description

 有考虑支持一下其他客户端的媒体下载吗？比如twitter的媒体可以直接分享到电报实现下载

### Suggested Solution

 有考虑支持一下其他客户端的媒体下载吗？比如twitter的媒体可以直接分享到电报实现下载

**Comment by tangyoha** [comment]
twitter 媒体目前没有计划支持
