### ISSUE TITLE
[Feature]: 希望能增加对频道的订阅功能

### ISSUE THREAD

**Issue by lancer-wang** [tangyoha/telegram_media_downloader#124]
### Description

对某个频道进行订阅，定时下载新内容

### Suggested Solution

初次订阅默认下载频道所有消息，或者记录这个频道最后一条消息的id
订阅之后，定时根据记录的最后一条id，下载频道的新内容，然后更新这个id

**Comment by tangyoha** [comment]
@lancer-wang  hi, listen_forward 满足不了你的需求吗？

**Comment by lancer-wang** [comment]
> listen_forward

listen_forward 可以监控频道新帖吗
应该怎么弄？

**Comment by tangyoha** [comment]
是监控转发还是监控下载？

**Comment by lancer-wang** [comment]
可以了，原来后面的那个是要跟被转发到的群
