### ISSUE TITLE
[Bug]: don't work hiddent number +888

### ISSUE THREAD

**Issue by GitBib** [tangyoha/telegram_media_downloader#127]
### telegram_media_downloader version or commit

2.2.3

### What OS are you seeing the problem on?

Mac

### Python Version

3.12.0

### What happened?

The account has a hidden number telegram (+888). But pyrogram does not know how to handle this number.

### Expected Behavior

Accounts with the number +888 work.

### Current Behavior

Now ValueError.
`ValueError: <class 'pyrogram.raw.types.auth.code_type_fragment_sms.CodeTypeFragmentSms'> is not a valid NextCodeType`

`
next_type=enums.NextCodeType(type(sent_code.next_type)) if sent_code.next_type else None,
              │     │                 │         │              │         └ <member 'next_type' of 'SentCode' objects>
              │     │                 │         │              └ pyrogram.raw.types.auth.SentCode(type=pyrogram.raw.types.auth.SentCodeTypeApp(length=5), phone_code_hash='80000000a00f00bafa'...
              │     │                 │         └ <member 'next_type' of 'SentCode' objects>
              │     │                 └ pyrogram.raw.types.auth.SentCode(type=pyrogram.raw.types.auth.SentCodeTypeApp(length=5), phone_code_hash='80000000a00f00bafa''...
              │     └ <enum 'NextCodeType'>
              └ <module 'pyrogram.enums' from '.../telegram_media_downloader/env/lib/python3.12/site-...
`

**Comment by GitBib** [comment]
the problem can be solved by upgrading pyrogram to or above 2.0.106.

**Comment by tangyoha** [comment]
@GitBib hi,try this version.
 pip3 install https://github.com/tangyoha/pyrogram/archive/refs/heads/master.zip

**Comment by GitBib** [comment]
@tangyoha It didn't work for me with this version.

**Comment by tangyoha** [comment]
@GitBib hi，this is above v2.0.106
