### ISSUE TITLE
[Bug]: Docker deployment error

### ISSUE THREAD

**Issue by huajideshutiao** [tangyoha/telegram_media_downloader#140]
### telegram_media_downloader version or commit

2.2.3

### What OS are you seeing the problem on?

Other Linux Distro

### What happened?

A bug happened!I updated the docker with the same configuration on unraid (6.12.2), but it did not work properly, checking the log with the following error:
WARNING  | __main__:download_all_chat:568 - Download wgetdownloadbot error: Telegram says: [400 BOT_METHOD_INVALID] - The method can't be used by bots (caused by "messages.GetHistory")

### Expected Behavior

Normal use

### Current Behavior

The telegram bot is not responding.

**Comment by bigm0re** [comment]
i have the same problem

**Comment by moonheart** [comment]
same here

**Comment by huajideshutiao** [comment]
Reply uniformly. To upgrade from the old version to 2.2.3, you need to clear the configuration file and modify the directory mapping. For details, refer to the current readme.

**Comment by huajideshutiao** [comment]
I have now rolled back because the docker occupancy for version 2.2.3 has almost doubled.
