### ISSUE TITLE
[Bug]:验证手机号这步时卡住

### ISSUE THREAD

**Issue by xueli12** [tangyoha/telegram_media_downloader#143]
### telegram_media_downloader version or commit

v2.2.3

### What OS are you seeing the problem on?

Windows

### Python Version

3.11

### What happened?

作者好，我到了验证手机号这步时就卡住了，连发送验证码的消息都没有。。。
Welcome to Pyrogram (version 2.0.64)
Pyrogram is free software and comes with ABSOLUTELY NO WARRANTY. Licensed
under the terms of the GNU Lesser General Public License v3.0 (LGPL-3.0).

Enter phone number or bot token: +86xxxxxx
Is "+86XXXXX" correct? (y/N): y

### Expected Behavior

期待答复

### Current Behavior

期待答复

**Comment by xueli12** [comment]
配置文件如下：

api_hash: XXXXXXXXXXXX
api_id: XXXXXXXXX
chat:
- chat_id: XXXXXXXXXXX
  last_read_message_id: 0
  download_filter: message_date >= 2022-12-01 00:00:00 and message_date <= 2024-01-17 00:00:00
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
media_types:
- audio
- photo
- video
- document
- voice
- video_note
# in linux please use /
save_path: Q:\telegram
proxy:
  scheme: socks5
  hostname: 127.0.0.1
  port: 10808
  
hide_file_name: true
file_name_prefix:
- message_id
- file_name
file_name_prefix_split: ' - '
max_download_task: 5
web_host: 127.0.0.1
web_port: 5000
language: EN
web_login_secret: 123
allowed_user_ids:
- 'me'
date_format: '%Y_%m'

**Comment by zcmi** [comment]
兄弟你是怎么解决的呀

**Comment by xiaozhubin** [comment]
我也卡在这一步了，请问怎么解决？

**Comment by xiaozhubin** [comment]
> 兄弟你是怎么解决的呀

哥们，这个问题你解决了吗？

**Comment by TaoRone** [comment]
> > 兄弟你是怎么解决的呀
> 
> 哥们，这个问题你解决了吗？

哥们，我也问下……你这个问题解决了么？
我猜是本地nas命令行没有走代理的原因，但是修改配置文件直接从docker内也无法访问

**Comment by TaoRone** [comment]
> > > 兄弟你是怎么解决的呀
> > 
> > 
> > 哥们，这个问题你解决了吗？
> 
> 哥们，我也问下……你这个问题解决了么？ 我猜是本地nas命令行没有走代理的原因，但是修改配置文件直接从docker内也无法访问

~~最后开了全局路由代理了……openclahs切换为fakeip模式~~

奇怪，发现trojan后台代理失败，ss会成功
api.telegram.org这一步会通过udp来代理么？
