### ISSUE TITLE
[Bug]: 使用机器人直接下载单条信息时, 如果信息中包含多个文件, 只下载第一个

### ISSUE THREAD

**Issue by polarbearsys** [tangyoha/telegram_media_downloader#150]
### telegram_media_downloader version or commit

v2.2.3

### What OS are you seeing the problem on?

Windows

### Python Version

3.11.6

### What happened?

参照https://github.com/tangyoha/telegram_media_downloader/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E6%9C%BA%E5%99%A8%E4%BA%BA%E4%B8%8B%E8%BD%BD#%E4%B8%8B%E8%BD%BD 这个教程的第七条, 给bot发送了一个消息连接, 这个消息中存在两个或更多音频视频或者图片, 但是只下载了第一个

### Expected Behavior

下载消息中的全部媒体

### Current Behavior

只下载第一个文件

**Comment by tangyoha** [comment]
@polarbearsys hi, 使用/download下载多个媒体， 直接发单个媒体只下一个
