### ISSUE TITLE
how to obtain a valid Telegram API key？

### ISSUE THREAD

**Issue by chenshuichuan** [tangyoha/telegram_media_downloader#154]
I use VPN to visit  https://my.telegram.org/apps ，
when I create application ，it‘s allways fail。pop： “my.telegram.org says：ERROR”
Have anyone else encountered this problem?

**Comment by chenshuichuan** [comment]
I I solved this problem through methods from this https://github.com/tdlib/telegram-bot-api/issues/273

**Comment by chenshuichuan** [comment]
I I solved this problem through methods from this https://github.com/tdlib/telegram-bot-api/issues/273

**Comment by wdwc2** [comment]
I tried their methods, but it still didn't work
