### ISSUE TITLE
[Feature]: Optimize Docker Image Volume

### ISSUE THREAD

**Issue by huajideshutiao** [tangyoha/telegram_media_downloader#161]
### Description

As the title suggests. 

### Suggested Solution

The deployment of the image in version 2.2.3 (600MB)is almost three times the size of the image in version 2.2.1 (164MB). This is really strange.
I hope the volume can be controlled between 200-300MB.

**Comment by tangyoha** [comment]
d6ad102282f8abee5b8df9151f569c3d16ad8252
