### ISSUE TITLE
[Bug]: 怀疑代理是否需要udp服务，才能访问api.telegram.org

### ISSUE THREAD

**Issue by TaoRone** [tangyoha/telegram_media_downloader#165]
### telegram_media_downloader version or commit

v2.2.3

### What OS are you seeing the problem on?

Other Linux Distro

### Python Version

CPython 3.11.2

### What happened?

前提：已经设置好后台代理和socks5代理
当后台openclash通过trojan进行代理，输入手机号后，会卡在获取验证码这一步
如果切换为ss（打开了udp），就可以畅通继续
是否api.telegram.org需要能udp访问的节点？

### Expected Behavior

RT

### Current Behavior

RT

### Possible Solution

1.建议增加一个设置项，即用户可以输入自己反代的tg api地址
2.增加提示，节点必须支持udp（个人怀疑）

**Comment by tangyoha** [comment]
@TaoRone hi, 应该是网络与telegram dn对应的服务器不通导致的
