### ISSUE TITLE
[Bug]: 个别群组 监听模式里 圆形即时视频无法抓取。

### ISSUE THREAD

**Issue by lgup** [tangyoha/telegram_media_downloader#167]
### telegram_media_downloader version or commit

最新版

### What OS are you seeing the problem on?

Other Linux Distro

### Python Version

前任

### What happened?

正常的docker搭建，开启监听转发模式，有两个问题。

1. 圆形即时视频，NOTE类型的，会监听失败，可是奇怪的是机器人那边显示成功，可是并没有转发，图片视频一切正常。
2. 目前剧透隐藏模式发送图片，无论手动自动怎样都无法下载。

### Expected Behavior

希望能够修正。

### Current Behavior

无法下载。

**Comment by tangyoha** [comment]
@lgup hi, try new version
