### ISSUE TITLE
 pyrogram-2.0.106 not working with me 

### ISSUE THREAD

**Issue by Romntic** [tangyoha/telegram_media_downloader#178]
### telegram_media_downloader version or commit

2.2.3

### What OS are you seeing the problem on?

Mac

### Python Version

3.12

### What happened?

2024-07-04 04:42:35.060 | WARNING  | __main__:download_all_chat:568 - Download -1002233024232 error: Peer id invalid: -1002233024232

### Expected Behavior

pyrogram-2.0.106 not working with me at Telegram Media Downloader 2.2.3

### Current Behavior

still not working with me 

### Possible Solution

update pyrogram

**Comment by xeye666** [comment]
同样问题，linux下，2.2.3版本docker，pyrogram2.0.64版本406错误无法登录，无法升级2.0.106版本

**Comment by 502milk** [comment]
> 同样问题，linux下，2.2.3版本docker，pyrogram2.0.64版本406错误无法登录，无法升级2.0.106版本

请先删除docker内的 sessions 文件夹，并进入容器升级pyrogram
（试试吧

**Comment by TaoRone** [comment]
更新了下镜像，同时也把镜像更新代码放出了，有兴趣可参考：
https://github.com/TaoRone/telegram_media_downloader

**Comment by tangyoha** [comment]
@Romntic hi, try new version, delete sessions dir and relogin pls.

**Comment by Romntic** [comment]
> @Romntic hi, try new version, delete sessions dir and relogin pls.

thanks in last version 2.2.4 
work perfect 
thanks
