### ISSUE TITLE
[Bug]: 已加入的私人频道无法下载

### ISSUE THREAD

**Issue by zpk1996** [tangyoha/telegram_media_downloader#179]
### telegram_media_downloader version or commit

2.2.3

### What OS are you seeing the problem on?

Windows

### Python Version

3.11.6

### What happened?

![image](https://github.com/tangyoha/telegram_media_downloader/assets/57736697/0ea89053-ea1d-44b3-a479-193a25461916)
![image](https://github.com/tangyoha/telegram_media_downloader/assets/57736697/87f5540c-fcea-4649-a60b-33c9bb38d540)
如图，我很确定加入了该私人频道，并且输入了正确的chat id，我可以使用telegram_media_downloader下载其他私人频道内的内容，但是这个频道无法下载，请问是什么原因？

### Expected Behavior

我希望可以正常下载该频道内的内容。

### Current Behavior

尝试其他频道，依旧正常，唯独此频道不行。

**Comment by Teomit** [comment]
This is because some groups are not saved to the media_downloader.session file. Change **module\pyrogram_extension.py**:

![GitHubDesktop_Wd5ObL1BIb](https://github.com/user-attachments/assets/7366fe1a-dfb0-463f-8634-544d384f1f88)

```python
            dialogs = []
            offset_date = 0
            offset_id = 0
            offset_peer = pyrogram.raw.types.InputPeerEmpty()
            limit = 100
            hash = 0

            while True:
                response = await self.invoke(pyrogram.raw.functions.messages.GetDialogs(
                    offset_date=offset_date,
                    offset_id=offset_id,
                    offset_peer=offset_peer,
                    limit=limit,
                    hash=hash
                ))

                dialogs.extend(response.dialogs)

                if len(response.dialogs) < limit:
                    break

                offset_peer = pyrogram.raw.types.InputPeerEmpty() if not response.dialogs else response.dialogs[-1].peer
                offset_id = response.messages[-1].id if response.messages else 0
                offset_date = response.messages[-1].date if response.messages else 0


```

**Comment by zpk1996** [comment]
> yrogram_extension.py

![image](https://github.com/user-attachments/assets/7b846254-2a7d-49ad-999a-3afd181879b4)
OK，and then another error (not invalid id,but invalid type)， can u help me pls?

**Comment by zpk1996** [comment]
Hi,Teomit

Thank u very much for helping me.

And I met another error. Like this pic, Invalid peer type:Channel.

Do u know how to deal with it? 

Thank u again.
















At 2024-07-13 20:36:16, "Teomit" ***@***.***> wrote:

This is because some groups are not saved to the media_downloader.session file. Try a python script. Save as a py file, e.g. fix.py. Then run it at the command line: python fix.py. Don't forget to substitute your path for media_downloader.session file, as well as api_id and api_hash

from telethon import TelegramClient
import os
import sqlite3
import datetime

api_id = 'YOUR_API_ID'
api_hash = 'YOUR_API_HASH'
session_path = 'r'C:\telegram_media_downloader\session\media_downloader.session'

client = TelegramClient('session_name', api_id, api_hash)

async def main():
    conn = sqlite3.connect(session_path)
    cursor = conn.cursor()

    with open('id.txt', 'w', encoding='utf-8') as file:
        async for dialog in client.iter_dialogs():
            name = dialog.name
            dialog_id = dialog.id
            dialog_type = type(dialog.entity).name
            
            entity = dialog.entity
            access_hash = entity.access_hash if hasattr(entity, 'access_hash') else 'N/A (Empty)'
            username = entity.username if hasattr(entity, 'username') else 'N/A'
            phone_number = entity.phone if hasattr(entity, 'phone') else 'N/A'
            last_update_on = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            
            info = (f'Name: {name}\n'
                    f'ID: {dialog_id}\n'
                    f'Type: {dialog_type}\n'
                    f'access_hash: {access_hash}\n\n')
            
            print(info)
            file.write(info)
            
            cursor.execute('SELECT * FROM peers WHERE id = ?', (dialog_id,))
            if not cursor.fetchone():
                cursor.execute('''
                INSERT INTO peers (id, access_hash, type, username, phone_number, last_update_on)
                VALUES (?, ?, ?, ?, ?, ?)
                ''', (dialog_id, access_hash, dialog_type, username, phone_number, last_update_on))
                conn.commit()

    conn.close()

with client:
    client.loop.run_until_complete(main())

**Comment by tangyoha** [comment]
@zpk1996 hi, 直接用最新版本试下

**Comment by zpk1996** [comment]
> @zpk1996 hi, 直接用最新版本试下

已解决。感谢~~

**Comment by cKwaming** [comment]
大哥，怎么解决的，2.2.5版本，好像也下不了那些私密群组，里面的视频也是不允许下载的。一样报格式错误

**Comment by zpk1996** [comment]
> 大哥，怎么解决的，2.2.5版本，好像也下不了那些私密群组，里面的视频也是不允许下载的。一样报格式错误

media_downloader.session的问题我也不太懂，换了2.2.5版本就自动解决了。重新从git上拉一下代码试试？
