### ISSUE TITLE
[Bug]: 一段时间后卡住

### ISSUE THREAD

**Issue by wzgrx** [tangyoha/telegram_media_downloader#183]
### telegram_media_downloader version or commit

244

### What OS are you seeing the problem on?

Windows

### Python Version

3.10.10

### What happened?

[00:08:35] WARNING  socket.send() raised exception.                                               proactor_events.py:352
[00:08:51] WARNING  socket.send() raised exception.                                               proactor_events.py:352
           WARNING  socket.send() raised exception.                                               proactor_events.py:352
           WARNING  socket.send() raised exception.                                               proactor_events.py:352
           WARNING  socket.send() raised exception.                                               proactor_events.py:352
           WARNING  socket.send() raised exception.                                               proactor_events.py:352
[00:09:06] WARNING  socket.send() raised exception.                                               proactor_events.py:352
           WARNING  socket.send() raised exception.                                               proactor_events.py:352
           WARNING  socket.send() raised exception.                                               proactor_events.py:352
           WARNING  socket.send() raised exception.                                               proactor_events.py:352
           WARNING  socket.send() raised exception.                                               proactor_events.py:352

### Expected Behavior

[00:08:35] WARNING  socket.send() raised exception.                                               proactor_events.py:352
[00:08:51] WARNING  socket.send() raised exception.                                               proactor_events.py:352
           WARNING  socket.send() raised exception.                                               proactor_events.py:352
           WARNING  socket.send() raised exception.                                               proactor_events.py:352
           WARNING  socket.send() raised exception.                                               proactor_events.py:352
           WARNING  socket.send() raised exception.                                               proactor_events.py:352
[00:09:06] WARNING  socket.send() raised exception.                                               proactor_events.py:352
           WARNING  socket.send() raised exception.                                               proactor_events.py:352
           WARNING  socket.send() raised exception.                                               proactor_events.py:352
           WARNING  socket.send() raised exception.                                               proactor_events.py:352
           WARNING  socket.send() raised exception.                                               proactor_events.py:352

### Current Behavior

[00:08:35] WARNING  socket.send() raised exception.                                               proactor_events.py:352
[00:08:51] WARNING  socket.send() raised exception.                                               proactor_events.py:352
           WARNING  socket.send() raised exception.                                               proactor_events.py:352
           WARNING  socket.send() raised exception.                                               proactor_events.py:352
           WARNING  socket.send() raised exception.                                               proactor_events.py:352
           WARNING  socket.send() raised exception.                                               proactor_events.py:352
[00:09:06] WARNING  socket.send() raised exception.                                               proactor_events.py:352
           WARNING  socket.send() raised exception.                                               proactor_events.py:352
           WARNING  socket.send() raised exception.                                               proactor_events.py:352
           WARNING  socket.send() raised exception.                                               proactor_events.py:352
           WARNING  socket.send() raised exception.                                               proactor_events.py:352

**Comment by Walkerby** [comment]
问题解决了嘛，我用docker出现同样的问题，过一段时间，大概几个小时就会出现 socket.send() raised exception

**Comment by zj1123581321** [comment]
同样也遇到了这个问题，，前几个月都是正常的。
