### ISSUE TITLE
v2.2.0 plan

### ISSUE THREAD

**Issue by tangyoha** [tangyoha/telegram_media_downloader#2]
## checklist

- [x] 下载页面展示 `v2.1.1`
- [x] 支持多频道下载 `v2.1.4`
- [x] 支持通过电报机器人下发指令，下载，转发，包括私有视频转发 `v2.1.6`
- [x] 支持指定`下载文件大小`,`日期`,`消息文本`,`消息id`,`视频质量`,`视频长度`过滤，`v2.1.3`。查阅 [如何使用下载过滤器](https://github.com/tangyoha/telegram_media_downloader/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E8%BF%87%E6%BB%A4%E5%99%A8)

## checklist

- [x] Download page display `v2.1.1`
- [x] Support multi-channel download `v2.1.4`
- [x] Support sending instructions, downloading, reposting, including private video reposting via telegram bot `v2.1.6`
- [x] Support specifying `download file size`, `date`, `message text`, `message id`, `video quality`, `video length` filtering, `v2.1.3`. Check out [How to use Filter](https://github.com/tangyoha/telegram_media_downloader/wiki/How-to-use-Filter)

**Comment by Romntic** [comment]
great job Now Telegram Media Downloader more professional 
Please if u can add option for download size maximum downloaded 
and make file save id number in save for example data.yaml

**Comment by tangyoha** [comment]
@Romntic hi, you can config  `download_filter` in `config.yaml`.
Like that:
```yaml
download_filter:
  'telegram_chat_id': media_file_size >= 10 * 1024 * 1024 && media_file_size <= 1024 * 1024 * 1024
```

For more usage, please see `https://github.com/tangyoha/telegram_media_downloader/wiki/How-to-use-Filter`
"what mean make file save id number in save for example data.yaml", what does this mean?

**Comment by Romntic** [comment]
great that mean size 1024 below download if more not download true ? if wand select between 1 mg to 900 mg ... if u can more explain to make more understand

**Comment by tangyoha** [comment]
download_filter:
  'telegram_chat_id': (media_file_size >= 10 * 1024 * 1024 && media_file_size <= 1024 * 1024 * 1024) && ( message_id >=1 && message_id <= 900)

**Comment by tangyoha** [comment]
> i need to make download from 8474 to 8547 only i make this filter but it's download from start 1 download_filter: telegram_chat_id: message_id >= 8474 && message_id <=8575

you can see https://github.com/tangyoha/telegram_media_downloader/wiki/How-to-use-Filter

**Comment by tangyoha** [comment]
in config
```yaml
chat_id: your_chat_id
download_filter:
   'your_chat_id': id >= 1 && id <= 900
```

**Comment by Romntic** [comment]
Thanks it's working 🙏🙏

**Comment by tmnext** [comment]
Great work. For macOS, 127.0.0.1:5000 (5000 is reserved for airplay), would be great if user can specify port in config.yaml.

**Comment by tangyoha** [comment]
@70m7E hi, see web_port

**Comment by xinmans** [comment]
any update?

**Comment by Viewofmind** [comment]
when we stop programe in between and start again showing error. how to restart again from it close
