### ISSUE TITLE
Some files are not downloaded in Windows because of forbidden characters in the name

### ISSUE THREAD

**Issue by Teomit** [tangyoha/telegram_media_downloader#21]
**Describe the bug**
Some files are not downloaded in Windows because of forbidden characters in the name. Symbols: <>:"/\\|?*

**Python Version**
Python: 3.11

**OS:**
Windows 10

**Comment by tangyoha** [comment]
To submit a bug fix, you need to specify a format, such as: fix: some file can... #21
