### ISSUE TITLE
Is there an easy way to migrate from Dineshkarthik's TMD?

### ISSUE THREAD

**Issue by nihelmasell** [tangyoha/telegram_media_downloader#30]
Hi, I've been using his software for almost a year now, but have noticed some connection issues and config.yaml corruption, apart from 0 bytes files... I understand your software is better at this. Is there a way to migrate without RE-DOWNLOADING? I got like 4tb of 64 channels. I created via a script a python environment for each and any of them. I noticed your software also has the option to download all channels at once. Do you have any idea on how can I migrate without redownloading, and also, attempting to download the 0 bytes that were missing because of Dineshkarthik´s version? Thanks in advance.

**Comment by tangyoha** [comment]
@nihelmasell  hi, Sorry, resources downloaded using Dineshkarthik's project cannot be migrated directly, you need to manually set `last_read_message_id` to avoid downloading to previous resources.

**Comment by nihelmasell** [comment]
There would be no problem with that. But doesn't your software check for existing files? I think I read in the issues section of your previous project that it would do it (compared to Dina's, which I think just replaces the files). That would be a great feature, if not yet implemented. Because I could just migrate easily, not having to worry about the last downloaded post; it would just skip existing files like gallery-dl or similar software if you configure them to. In any case, I would like to know how the project behaves when a file with the same name is found (given you configured the naming scheme as Dina's). Thanks in advance.

**Comment by tangyoha** [comment]
Thank you very much for your suggestion, the behavior of the project when a file with the same name is found, our setting is to skip the file, but our version will add the id of the message in front of the file name by default. We are different in naming of pictures and Dineshkarthik.

**Comment by nihelmasell** [comment]
Thank you very much for your answer. Is there any way actually to use the naming convention used by Dineshkarthik? For example "photo_2020-10-24_18-07-29_71409968272408XXXXX" and "video_2022-03-06_08-26-10_71410113004724XXXXX". I didn't fully understand that part of the documentation, but I think it is possible for the name of the files to be changed.

I also noticed that some files downloaded by the other project use no naming scheme at all, like "IMG_0037.mov" or "Sequence 04_10.mp4". How would your project react in that scenario? Using the original filename or renaming it?

Thanks in advance.

**Comment by tangyoha** [comment]
It's hard to explain why it doesn't work. Part of the reason is that the command rules have changed in this project. For example, if the file name of the picture is empty in the server, the default is file id. Our command starts with message id by default to avoid downloading the same file The name needs to be renamed, it is difficult to use it smoothly from the old version, unless you manually set the last_read_message_id.If it is the same file name, we do not provide other options, the default is to skip.
