### ISSUE TITLE
not working after that 

### ISSUE THREAD

**Issue by Romntic** [tangyoha/telegram_media_downloader#4]
Hello 
i download last version 2.1.2 
but explain in picture 
![Screen Shot 2023-02-13 at 9 29 21 PM](https://user-images.githubusercontent.com/31198048/218544215-569d7d5f-342b-4395-a6d3-5f0d61c4e110.png)

**Comment by tangyoha** [comment]
@Romntic hi, Prompt to update the version, this problem has just been solved.

**Comment by Romntic** [comment]
yes thanks for u support 
amazing developer
