### ISSUE TITLE
Do not use pre-created config.yaml and data.yaml files because of the difficulty of updating.

### ISSUE THREAD

**Issue by Teomit** [tangyoha/telegram_media_downloader#41]
**Is your feature request related to a problem? Please describe.**
When I update a program from the git, I have to manually restore the files: config.yaml and data.yaml

**Describe the solution you'd like**
I recommend not including these files in git. Their existence should be checked when I run the script. If they don't exist, the script should ask for api_hash, api_id and chat_id and create these files from the template.

**Comment by tangyoha** [comment]
Thanks for your suggestion, it will be added in the next version
