### ISSUE TITLE
增加自带定时触发下载任务的功能

### ISSUE THREAD

**Issue by shoaky009** [tangyoha/telegram_media_downloader#44]
目前是用k3s cronjob来触发下载，跑完就没了webui的一些进度也看不了。
可以在启动项里增加一个选项来定义？默认不增加就是现有的模式

**Comment by tangyoha** [comment]
能否描述的更加清楚些呢

**Comment by shoaky009** [comment]
> 能否描述的更加清楚些呢

和#50 类似的，启动参数或配置上有定义定时器就运行在常驻模式，如果没有就还是照旧运行完就退出

**Comment by tangyoha** [comment]
需求重复
