### ISSUE TITLE
[Feature]: 希望能判断文件名是否过长，过长的把超过的删了。

### ISSUE THREAD

**Issue by jerryc127** [tangyoha/telegram_media_downloader#67]
### Description

文件名过长 会导致无法下载
希望能判断文件名是否过长，过长的把超过的删了。

### Suggested Solution

文件名过长 会导致无法下载
希望能判断文件名是否过长，过长的把超过的删了。

### Additional Context

![image](https://github.com/tangyoha/telegram_media_downloader/assets/16351105/0e1e65b8-8c9b-4a98-8797-5c154df33bc2)

**Comment by tangyoha** [comment]
忘了还有.temp，在2.1.8修复该问题
