### ISSUE TITLE
[Bug]: docker部署时无法出现验证手机号和验证码的步骤

### ISSUE THREAD

**Issue by fzucs** [tangyoha/telegram_media_downloader#75]
### telegram_media_downloader version or commit

v2.1.9

### What OS are you seeing the problem on?

Other Linux Distro

### Python Version

3.8.10

### What happened?

用的docker运行，不知道是什么原因出现了如下图的问题，界面卡着不动，并且显示时间和系统时间也不一样。等了十几分钟还是没有动静。用的是1c1g的小鸡，系统是ubuntu20.04.4 LTS。
![image](https://github.com/tangyoha/telegram_media_downloader/assets/100392795/09a0054c-c5ba-49de-96f6-304653f7dbbe)

### Expected Behavior

能够正常运行

### Current Behavior

无法出现验证手机号和代码

**Comment by tangyoha** [comment]
换个shell工具

**Comment by fzucs** [comment]
> 换个shell工具

真的可以了，谢谢大佬！！原来这个也有影响。现在还有个问题，就是输入ip:5000显示已拒绝连接。config.yaml里面设置了web_host: 127.0.0.1，web_port: 5000，宝塔里也开放了5000端口，状态显示为正常。这是什么原因呢，请大佬帮忙看看

**Comment by tangyoha** [comment]
web_host： 0.0.0.0

**Comment by fzucs** [comment]
> web_host： 0.0.0.0

好的谢谢大佬！
