### ISSUE TITLE
[Feature]: 支持解析出video下的超链接视频名称

### ISSUE THREAD

**Issue by aprilz-code** [tangyoha/telegram_media_downloader#79]
### Description

视频下视频描述是蓝色超链接。希望能得到[http://t.me/SDD/SD](ABC) ，得到ABC作为下载的视频名称

### Suggested Solution

视频下视频描述是蓝色超链接。希望能得到[http://t.me/SDD/SD](ABC) ，得到ABC作为下载的视频名称

**Comment by tangyoha** [comment]
ABC是什么

**Comment by tangyoha** [comment]
目前pyrogram无法支持该功能
