### ISSUE TITLE
[Feature]: Getting text from the posts

### ISSUE THREAD

**Issue by nihelmasell** [tangyoha/telegram_media_downloader#82]
### Description

Sometimes (if not always) images without context mean nothing. I would like a feature to be added, so a text file is attached to each downloaded file, using the description used by the uploader. Scraping TG with wget or archivebox is often messy, as you get repeated posts in one page. So if one could have the original description for each file it would be great. 

### Suggested Solution

I don't know. The telegram posts seem to have a unique html viewable on the web, like 5089.html, after the channel’s url. Maybe that can be used. 

### Additional Context

I know someone mentioned this before, but I saw no response.

**Comment by tangyoha** [comment]
You said that someone has said this question which one are you referring to?

**Comment by nihelmasell** [comment]
> You said that someone has said this question which one are you referring to?

This one https://github.com/tangyoha/telegram_media_downloader/issues/77 

I think he's pointing out the same enhancement.

**Comment by tangyoha** [comment]
We can put the caption into file name.But file name have a 255 length limit.just see `file_name_prefix` which you can configure in config.yaml.

**Comment by nihelmasell** [comment]
> We can put the caption into file name.But file name have a 255 length limit.just see `file_name_prefix` which you can configure in config.yaml.

Like this, for example?

file_name_prefix:
- message_id
- file_name
- caption

Or do I need to modify anything else?

**Comment by tangyoha** [comment]
Nothing else

**Comment by nihelmasell** [comment]
> Nothing else

Well, doesn't seem to work. I still get message ID and filename, and caption is not added. Does it truncate the caption when it's longer than 256 characters or just omits it? The program overall works very well and I didn't have to create python virtual environments, just add all the channel to config.yaml. But, well, this feature would be awesome, mostly when you have to grab images and videos not in a language you know.

**Comment by tangyoha** [comment]
truncate the caption

**Comment by tangyoha** [comment]
Might need to save to a file separately?

**Comment by nihelmasell** [comment]
> Might need to save to a file separately?

No, the captions are not saved at all. I backup more than 60 channels and have seen no caption added to the filenames in my latest download batch. You can do that in the future (saving it as a separate file) but now it doesn't even work for me (on macOS) the setting for the captions added to the filename.

**Comment by tangyoha** [comment]
1.show me your config
2.which program version does you use
3.If you are downloading a group of videos or pictures, you need to download the first one, and the name of the next downloaded file can have the title
