### ISSUE TITLE
[Bug]: try upgrade and new download but same 

### ISSUE THREAD

**Issue by Romntic** [tangyoha/telegram_media_downloader#90]
### telegram_media_downloader version or commit

2.2.0

### What OS are you seeing the problem on?

Mac

### Python Version

3.11

### What happened?

Hello How are ? 
first thanks for all u Hard Work 
i try upgrade script and install new script but same result its give me Old version 2.1.9 
Not 2.2.0

         
![Screen Shot 2023-06-29 at 9 24 59 PM](https://github.com/tangyoha/telegram_media_downloader/assets/31198048/efb71a55-75ae-4524-b8bb-75a93c7f9723)

### Expected Behavior

not update the file may be or something i missed

### Current Behavior

not give me 2.2.0

**Comment by tangyoha** [comment]
fix
