### ISSUE TITLE
[Feature]: 电报讨论组视频能否支持下载？

### ISSUE THREAD

**Issue by hh3016** [tangyoha/telegram_media_downloader#94]
### Description

https://t.me/youzididi1234/3164?comment=28414

📥 Downloading: 0.0b
├─ 📁 Total: 1
├─ ✅ Success: 0
├─ ❌ Failed: 0
└─ ⏩ Skipped: 1
请问下。讨论组的视频机器人能支持下载吗。如果能。要如何配置呢。谢谢

### Suggested Solution

支持电报讨论组视频地址下载。

**Comment by tangyoha** [comment]
https://t.me/youzididi1234/3164
