### ISSUE TITLE
[Feature]: Filter listen_forward message by sender

### ISSUE THREAD

**Issue by djkilroy** [tangyoha/telegram_media_downloader#95]
### Description

Is it possible to filter listen_forward message by sender.

### Suggested Solution

Add a filter sender id at the back of the listen_forward command.
e.g. /listen_forward https://t.me/c/a https://t.me/c/b  file_size > 10KB filter_sender [sender_id]

**Comment by tangyoha** [comment]
https://github.com/tangyoha/telegram_media_downloader/commit/cf7a2b864897d698b91d97fb4d9b1e284daed248
